### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by tjfortruelove** [Ho-Van-Con/Report-Computer-Vision---Project#1]
[main_with_error.pdf](https://github.com/Ho-Van-Con/Report-Computer-Vision---Project/files/3935309/main_with_error.pdf)

**Comment by hovancon-zz** [comment]
- Cái **listing** là cái danh mục code á nếu không cần thiết thì xóa thôi.

**Comment by hovancon-zz** [comment]
Xong nha Toàn
