### ISSUE TITLE
Comment tiểu luận

### ISSUE THREAD

**Issue by truongtrilac** [Ho-Van-Con/Report-Computer-Vision---Project#2]
1. "Nhóm xin chân thành cảm ơn, trân trọng" căn lề phải ... page 5
2. Tài liệu tham khảo: [2] Nguyễn Đức Thành.... page 33

**Comment by hovancon-zz** [comment]
Page 5 khỏi canh cũng được mà.
Để sửa lại cái tài liêu thanh khảo.

**Comment by hovancon-zz** [comment]
Xong nha Lạc
